### ISSUE TITLE
wdth: use axis units as percent of regular

### ISSUE THREAD

**Issue by davelab6** [agyeiarcher/Crispy-VF#31]
`wdth` today goes from min 1, default 1, max 1,000, which is **invalid** per OT 1.8.3 spec, which says start with a default, that is 100%, and min and max are percentages relative to that. 

So you need to pick a good default and calculate what the min and max are, and correct those values

**Comment by agyeiarcher** [comment]
is the default mandatorily halfway between min and max width?

**Comment by davelab6** [comment]
No, it isn't half way; even if the max was 200, you could still have 50/100/200 or 1/100/110 or whatever
