### ISSUE TITLE
[ERROR] com.google.fonts/check/varfont_instance_coordinates

### ISSUE THREAD

**Issue by felipesanches** [agyeiarcher/Crispy-VF#35]
Fontbakery version: 0.7.15.dev3+gec569215
(PR #34)

<details>
<summary>💔 <b>ERROR:</b> Check variable font instances have correct coordinate values</summary>

* [com.google.fonts/check/varfont_instance_coordinates](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/varfont_instance_coordinates)

* 💔 **ERROR** Failed with KeyError: 'grad'
* 🔥 **FAIL** Instance "Default" wght value is "1.0". It should be "400.0" [code: bad-coordinate]
* 🔥 **FAIL** Instance "Default" wdth value is "1.0". It should be "100.0" [code: bad-coordinate]

</details>

**Comment by felipesanches** [comment]
This looks like a fontbakery bug. I will try to fix it and let you know when we have it working properly again.

**Comment by agyeiarcher** [comment]
closing this now, will check on status of the error on my next fontbakery check
