### ISSUE TITLE
[FAIL] com.google.fonts/check/fstype

### ISSUE THREAD

**Issue by felipesanches** [agyeiarcher/Crispy-VF#37]
Fontbakery version: 0.7.15.dev3+gec569215

----
<summary>🔥 <b>FAIL:</b> Checking OS/2 fsType.</summary>

* [com.google.fonts/check/fstype](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/fstype)

* 🔥 **FAIL** OS/2 fsType is a legacy DRM-related field.
In this font it is set to 4 meaning that:
The font may be embedded, and temporarily loaded on the remote system, but documents that use it must not be editable.

No such DRM restrictions can be enabled on the Google Fonts collection, so the fsType field must be set to zero (Installable Embedding) instead.
Fonts with this setting indicate that they may be embedded and permanently installed on the remote system by an application.

More detailed info is available at:
https://docs.microsoft.com/en-us/typography/opentype/spec/os2#fstype [code: drm]

----
**Note:** This [fontbakery](https://font-bakery.readthedocs.io/en/latest/) check FAIL needs to be fixed before submitting this font project for a final review to be included on the Google Fonts collection.
(PR #34)

**Comment by felipesanches** [comment]
@agyeiarcher, are you applying fixes to these issues that you are closing? I don't see them at the master branch.

**Comment by agyeiarcher** [comment]
hey @felipesanches I'm making the changes locally. Would like to start 'clean' with a proper build and continue editing from there one prob at a time 'live' on Travis CI

**Comment by felipesanches** [comment]
OK, cool ;-)
