### ISSUE TITLE
[FAIL] com.google.fonts/check/name/subfamilyname

### ISSUE THREAD

**Issue by felipesanches** [agyeiarcher/Crispy-VF#42]
Fontbakery version: 0.7.15.dev3+gec569215

----
<summary>🔥 <b>FAIL:</b> Check name table: FONT_SUBFAMILY_NAME entries. </summary>

* [com.google.fonts/check/name/subfamilyname](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/name/subfamilyname)

* 🔥 **FAIL** SUBFAMILY_NAME for Mac "Regular" must be "" [code: bad-familyname]

----
**Note:** This [fontbakery](https://font-bakery.readthedocs.io/en/latest/) check FAIL needs to be fixed before submitting this font project for a final review to be included on the Google Fonts collection.
(PR #34)

**Comment by felipesanches** [comment]
`must be ""` does not sound right. I will have to review this check and possibly fix fontbakery...

**Comment by agyeiarcher** [comment]
Checking in on this, should I skip this check?
