### ISSUE TITLE
[FAIL] com.google.fonts/check/smart_dropout

### ISSUE THREAD

**Issue by felipesanches** [agyeiarcher/Crispy-VF#43]
Fontbakery version: 0.7.15.dev3+gec569215

----
<summary>🔥 <b>FAIL:</b> Font enables smart dropout control in "prep" table instructions?</summary>

* [com.google.fonts/check/smart_dropout](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/smart_dropout)

* 🔥 **FAIL** The 'prep' table does not contain TrueType instructions enabling smart dropout control. To fix, export the font with autohinting enabled, or run ttfautohint on the font, or run the `gftools fix-nonhinting` script. [code: lacks-smart-dropout]

----
**Note:** This [fontbakery](https://font-bakery.readthedocs.io/en/latest/) check FAIL needs to be fixed before submitting this font project for a final review to be included on the Google Fonts collection.
(PR #34)

**Comment by agyeiarcher** [comment]
good to just add $ _gftools fix-nonhinting FontIn.ttf FontOut.ttf_ to the build script?

**Comment by felipesanches** [comment]
> good to just add $ gftools fix-nonhinting FontIn.ttf FontOut.ttf to the build script?

yes! That's a good way of addressing this :-)
