### ISSUE TITLE
[FAIL] com.google.fonts/check/varfont_instance_names

### ISSUE THREAD

**Issue by felipesanches** [agyeiarcher/Crispy-VF#45]
Fontbakery version: 0.7.15.dev3+gec569215

----
<summary>🔥 <b>FAIL:</b> Check variable font instances have correct names</summary>

* [com.google.fonts/check/varfont_instance_names](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/varfont_instance_names)

* 🔥 **FAIL** Instance name "Default" is incorrect. It should be "" [code: bad-name]
* 🔥 **FAIL** This will cause problems with some of the Google Fonts systems that look up fonts by their style names. This must be fixed! [code: bad-instance-names]

----
**Note:** This [fontbakery](https://font-bakery.readthedocs.io/en/latest/) check FAIL needs to be fixed before submitting this font project for a final review to be included on the Google Fonts collection.
(PR #34)

**Comment by agyeiarcher** [comment]
Is this same as [44](https://github.com/agyeiarcher/Crispy-VF/issues/44)?
