### ISSUE TITLE
[FAIL] com.google.fonts/check/ots

### ISSUE THREAD

**Issue by felipesanches** [agyeiarcher/Crispy-VF#47]
Fontbakery version: 0.7.15.dev3+gec569215

----
<summary>🔥 <b>FAIL:</b> Checking with ots-sanitize.</summary>

* [com.google.fonts/check/ots](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/universal.html#com.google.fonts/check/ots)

* 🔥 **FAIL** ots-sanitize returned an error code (1). Output follows:

ERROR: Layout: Bad lookup offset 0 for lookup 0
ERROR: GSUB: Failed to parse lookup list table
ERROR: GSUB: Failed to parse table
Failed to sanitize file!

----
**Note:** This [fontbakery](https://font-bakery.readthedocs.io/en/latest/) check FAIL needs to be fixed before submitting this font project for a final review to be included on the Google Fonts collection.
(PR #34)

**Comment by agyeiarcher** [comment]
good fix for this would be adding 

$ ./ots-sanitize ttf_or_otf_file [transcoded_file] to build?

**Comment by felipesanches** [comment]
No. Fontbakery itself runs ots. The ERROR messages in the description of this issue are what ots has detected.

**Comment by felipesanches** [comment]
Or do you mean ots auto-fixes files? I am not aware of it.

**Comment by davelab6** [comment]
OTS does autofix, but by brutally dropping any data it FAILs. We want to **strongly** avoid any OTS issues.
