### ISSUE TITLE
[FAIL] com.google.fonts/check/unwanted_tables

### ISSUE THREAD

**Issue by felipesanches** [agyeiarcher/Crispy-VF#48]
Fontbakery version: 0.7.15.dev3+gec569215

----
<summary>🔥 <b>FAIL:</b> Are there unwanted tables?</summary>

* [com.google.fonts/check/unwanted_tables](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/universal.html#com.google.fonts/check/unwanted_tables)
<pre>--- Rationale ---
Some font editors store source data in their own SFNT
  tables, and these can sometimes sneak into final release files,
  which should only have OpenType spec tables.</pre>

* 🔥 **FAIL** The following unwanted font tables were found:
Table: MVAR
Reason: Produces a bug in DirectWrite which causes https://bugzilla.mozilla.org/show_bug.cgi?id=1492477, https://github.com/google/fonts/issues/2085

They can be removed by using fonttools/ttx.

----
**Note:** This [fontbakery](https://font-bakery.readthedocs.io/en/latest/) check FAIL needs to be fixed before submitting this font project for a final review to be included on the Google Fonts collection.
(PR #34)

**Comment by davelab6** [comment]
@agyeiarcher I believe the build script needs to be update to remove this table, eg `ttx -e MVAR font.ttf`

**Comment by agyeiarcher** [comment]
@davelab6 thanks Dave—anywhere additional to the [FontTools doc](https://fonttools.readthedocs.io/en/latest/ttx.html?highlight=ttx#ttx-from-opentype-and-truetype-to-xml-and-back) you'd recommend to learn more about ttx?

**Comment by davelab6** [comment]
MVAR is now allowed
