### ISSUE TITLE
[FAIL] com.google.fonts/check/whitespace_widths

### ISSUE THREAD

**Issue by felipesanches** [agyeiarcher/Crispy-VF#49]
Fontbakery version: 0.7.15.dev3+gec569215

----
<summary>🔥 <b>FAIL:</b> Whitespace and non-breaking space have the same width?</summary>

* [com.google.fonts/check/whitespace_widths](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/hmtx.html#com.google.fonts/check/whitespace_widths)

* 🔥 **FAIL** Whitespace and non-breaking space have differing width: Whitespace (space) is 140 font units wide, non-breaking space (nbspace) is 406 font units wide. Both should be positive and the same. [code: different-widths]

----
**Note:** This [fontbakery](https://font-bakery.readthedocs.io/en/latest/) check FAIL needs to be fixed before submitting this font project for a final review to be included on the Google Fonts collection.
(PR #34)

**Comment by agyeiarcher** [comment]
This feels like a good thing to automate. Is there already a pre-build checker/fixer script on open source for this?

**Comment by felipesanches** [comment]
I don't think there's already an auto-fixer for this. But if one implements such a thing, it should ideally be auto-fixing the `.glyphs` files, instead of the TTFs. So, yeah, it should be "pre-build" indeed.

**Comment by davelab6** [comment]
https://github.com/googlefonts/gf-glyphs-scripts or https://github.com/m4rc1e/mf-glyphs-scripts might have something, but actually the `=` metrics feature of GlyphsApp should be sufficient.

**Comment by agyeiarcher** [comment]
easy fix for this is:

af = AllFonts()
for f in af:
    f["nbspace"].width = f["space"].width
    f["nbspace"].changed()
    f.save()

Added to the sources/scripts folder but likely not needed
