### ISSUE TITLE
[WARN] com.google.fonts/check/gpos_kerning_info

### ISSUE THREAD

**Issue by felipesanches** [agyeiarcher/Crispy-VF#53]
Fontbakery version: 0.7.15.dev3+gec569215

----
<summary>⚠ <b>WARN:</b> Does GPOS table have kerning information?</summary>

* [com.google.fonts/check/gpos_kerning_info](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/gpos.html#com.google.fonts/check/gpos_kerning_info)

* ⚠ **WARN** GPOS table lacks kerning information. [code: lacks-kern-info]

----
**Note:** This [fontbakery](https://font-bakery.readthedocs.io/en/latest/) check WARN should ideally be addressed before submitting this font project for a final review to be included on the Google Fonts collection.
(PR #34)

**Comment by davelab6** [comment]
@agyeiarcher are you expecting to do any kerning? I can see some pairs like `TA` could use it

**Comment by agyeiarcher** [comment]
@davelab6 yeah I think so as well. I can begin on adding this information. Would like to have a chat with Ben about it, to establish a good standard for moving forward. Or is there someone internal to GF you'd recommend?
