### ISSUE TITLE
Convert indd proof to DrawBot?

### ISSUE THREAD

**Issue by davelab6** [agyeiarcher/Crispy-VF#66]
The filename `Crispy proof template to be scripted.indd` suggests there is an issue to script that layout in DrawBot? :)

https://github.com/agyeiarcher/Crispy-VF/blob/master/sources/documentation/proofs/Crispy%20proof%20template%20to%20be%20scripted.indd

**Comment by agyeiarcher** [comment]
Yep! That’s the plan :)

It’s the Cooper Type basic proof, which would also be nice to ‘give back’
to students to automate proofing into their workflows

AS
