### ISSUE TITLE
Unpack ZIPs

### ISSUE THREAD

**Issue by davelab6** [agyeiarcher/Crispy-VF#67]
ZIP files (eg `/sources/designspaces/SOURCE PARAMETRIC MASTERS-old.zip`) should not be checked into Github repos; when transferring a repo, all the data is transparently zipped and unzipped at transfer time, and the archival data is all stored in [packfiles](https://git-scm.com/book/en/v2/Git-Internals-Packfiles) :)

ZIPs prevent file name search from working, `git blame` and similar history metadata from working, etc... :)

**Comment by agyeiarcher** [comment]
Thanks Dave, didn't know this!
